# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 740ce72b5ee319b769c17b7ddb5ffd5395021fa551411c8d7415b153ac756be700c80dda385fbcd103d1218672fa42c9caef625f67af10547763baede9e09999

test:
  secret_key_base: 3f097f55aefba2b2370b3ed690c33c298fd37fe504c7267d691d1a663ac157b30cc0a32d2d227e348451aad4ed112470721f4423ba7f18b674f5ca6d5c6031a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
